trigger:
- master

variables:
  DisplayVersion: $[counter(variables['DisplayPrefix'], 1)]

stages:
- stage: format
  displayName: 'format'
  jobs:
  - job: format
    displayName: 'clang'
    pool: 'self-hosted'
    steps:
    - template: ./templates/format-check.yml
- stage: build
  dependsOn: format
  displayName: 'build'
  jobs:
  - job: build
    displayName: 'standard'
    pool: 'self-hosted'
    strategy:
      maxParallel: 10
      matrix:
        linux:
          BuildSuffix: 'linux-flatpak'
          ScriptFolder: 'linux-flatpak'
    steps:
    - template: ./templates/sync-source.yml
      parameters:
        artifactSource: $(parameters.artifactSource)
        needSubmodules: 'true'   
    - template: ./templates/build-flatpak-single.yml
      parameters:
        artifactSource: 'false'
        cache: 'true'
        version: $(DisplayVersion)
        env:
          FLATPAK_ENC_IV: $(FLATPAK_ENC_IV)
          FLATPAK_ENC_K: $(FLATPAK_ENC_K)
          FLATPAK_GPG_PUBLIC_KEY: $(FLATPAK_GPG_PUBLIC_KEY)
          FLATPAK_SSH_HOSTNAME: $(FLATPAK_SSH_HOSTNAME)
          FLATPAK_SSH_LOCATION: $(FLATPAK_SSH_LOCATION)
          FLATPAK_SSH_PORT: $(FLATPAK_SSH_PORT)
          FLATPAK_SSH_PUBLIC_KEY: $(FLATPAK_SSH_PUBLIC_KEY)
          FLATPAK_SSH_USER: $(FLATPAK_SSH_USER)
